[package]
name = "seq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtor = { git = "https://github.com/importwu/rtor.git" }
lazy_static = "1.4.0"